import Sidebar from "@/shared/organism/sidebar";
import type { Metadata } from "next";
import "./globals.css";

import { Inter } from "next/font/google";
import NavigationBar from "@/shared/organism/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "AB DIGI",
  // icons: "/vercel.svg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* content wrapper: sidebar (fixed width) + main (flexible) */}
        <div className="flex flex-1 min-h-0">
          {/* Sidebar: beri lebar tetap dan jangan biarkan mengecil */}
          <aside className="flex-shrink-0">
            <Sidebar />
          </aside>
          <NavigationBar />

          {/* Main: ambil sisa space, gunakan min-w-0 & overflow-auto untuk scroll dan mencegah overlap */}
          <main className="flex-1 min-w-0 bg-gray-100 overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
