import Sidebar from "@/shared/organism/sidebar";
import type { Metadata } from "next";
import "./globals.css";

import NavigationBar from "@/shared/organism/navbar";
import { Inter } from "next/font/google";
import Providers from "./provider/page";
import GlobalSpinner from "@/shared/organism/spinner-loading";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "AB DIGI",
  // icons: "/vercel.svg",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased min-h-screen flex`}>
        <Providers>
          <GlobalSpinner />
          {/* Sidebar: beri lebar tetap dan jangan biarkan mengecil */}
          <aside className="flex-shrink-0">
            <Sidebar />
          </aside>
          <div className="flex flex-col flex-1 min-w-0">
            <NavigationBar />

            {/* Main: ambil sisa space, gunakan min-w-0 & overflow-auto untuk scroll dan mencegah overlap */}
            <main className="flex-1 p-6 bg-gray-100 overflow-auto">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
